_BASE_: "Base-FSOD-C4.yaml"
MODEL:
  WEIGHTS: "./output/fsod/R_101_C4_1x/model_0039999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res2", "res3", "res4"]
OUTPUT_DIR: './output/fsod/R_101_C4_1x'
